CREATE TABLE IF NOT EXISTS people (
  id SERIAL NOT NULL PRIMARY KEY,
  full_name VARCHAR(255) NOT NULL,
  age INT NOT NULL,
  balance INT DEFAULT 0,
  email VARCHAR(255) NOT NULL,
  address VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS address (
  id INT NOT NULL PRIMARY KEY,
  line_1 VARCHAR(255) NOT NULL,
  line_2 VARCHAR(255),
  city VARCHAR(50) NOT NULL,
  postcode VARCHAR(9) NOT NULL
);